### ISSUE TITLE
Error in win32_api.hpp

### ISSUE THREAD

**Issue by FlowzZz** [boostorg/interprocess#99]
Hello,
I try to compile one of my project after upgrading to v16.3.4 of VS2019.
Context :
- Building with Release x64
- Boost 1.71.0 (compiled with vcpkg)

I get these errors :
1>...\vcpkg_VS2019\installed\x64-windows\include\boost\interprocess\detail\win32_api.hpp(925,51): error C2116: 'CreateSemaphoreA': function parameter lists do not match between declarations
1>...\vcpkg_VS2019\installed\x64-windows\include\boost\winapi\semaphore.hpp(25): message : see declaration of 'CreateSemaphoreA'
1>...\vcpkg_VS2019\installed\x64-windows\include\boost\interprocess\detail\win32_api.hpp(925,51): error C2733: 'CreateSemaphoreA': you cannot overload a function with 'C' linkage
1>...\vcpkg_VS2019\installed\x64-windows\include\boost\winapi\semaphore.hpp(25,1): message : see declaration of 'CreateSemaphoreA'
1>...\vcpkg_VS2019\installed\x64-windows\include\boost\interprocess\detail\win32_api.hpp(932,49): error C2116: 'GetSystemInfo': function parameter lists do not match between declarations
1>...\vcpkg_VS2019\installed\x64-windows\include\boost\winapi\system.hpp(31): message : see declaration of 'GetSystemInfo'
1>D:\Commun\Codes\vcpkg_VS2019\installed\x64-windows\include\boost\interprocess\detail\win32_api.hpp(932,49): error C2733: 'GetSystemInfo': you cannot overload a function with 'C' linkage

Is this a known problem ?

**Comment by ecatmur** [comment]
In the absence of a better solution, it would be a good idea to document the use of this compile option alongside https://github.com/boostorg/interprocess/blob/4a57769910cfbc2dc36fefa239c1482f77825ff3/doc/interprocess.qbk#L6671

**Comment by igaztanaga** [comment]
After:

* Careful use of Boost.Winapi and use of SetFilePointer instead of SetFilePointerEx (which requires a _LARGE_INTEGER by value that difficults the use of windows.h in certain circustances)
* Added tests to verify windows.h inclusion without BOOST_USE_WINDOWS_H does not break things

the issue seems to be solved. Many thanks for the report!

**Comment by k15tfu** [comment]
@igaztanaga Which version of Windows SDK did you use when testing?

**Comment by igaztanaga** [comment]
I compiled the change with multiple Visual Studio versions from Visual 2010 to Visual 2019. In Visual 2019 I think the latest SDK version installed was 10.0.17763.0
