### ISSUE TITLE
Regression on macOS: `os_thread_functions.hpp: error: 'pthread_threadid_np' was not declared in this scope; did you mean 'pthread_is_threaded_np'?`

### ISSUE THREAD

**Issue by barracuda156** [boostorg/interprocess#283]
`pthread_threadid_np` does not exist on all macOS versions.

```
:info:build darwin.compile.c++ bin.v2/libs/log/build/darwin-16.1.0/release/power_32/threading-multi/visibility-hidden/posix/ipc_reliable_message_queue.o
:info:build     "/opt/local/bin/g++-mp-16"  -ftemplate-depth-1024 -fvisibility-inlines-hidden -Os -std=gnu++17 -D_GLIBCXX_USE_CXX11_ABI=0 -arch ppc  -fPIC -m32 -O3 -Wall -fvisibility=hidden -dynamic -gdwarf-2 -fexceptions -Wno-inline  -DBOOST_ALL_NO_LIB=1 -DBOOST_ATOMIC_DYN_LINK=1 -DBOOST_ATOMIC_NO_LIB=1 -DBOOST_CHRONO_DYN_LINK=1 -DBOOST_CHRONO_NO_LIB=1 -DBOOST_CONTAINER_DYN_LINK=1 -DBOOST_CONTAINER_NO_LIB=1 -DBOOST_DATE_TIME_DYN_LINK=1 -DBOOST_DATE_TIME_NO_LINK=1 -DBOOST_EXCEPTION_NO_LIB=1 -DBOOST_FILESYSTEM_DYN_LINK=1 -DBOOST_FILESYSTEM_NO_LIB=1 -DBOOST_LOG_BUILDING_THE_LIB=1 -DBOOST_LOG_DLL -DBOOST_LOG_USE_NATIVE_SYSLOG -DBOOST_LOG_WITHOUT_DEBUG_OUTPUT -DBOOST_LOG_WITHOUT_EVENT_LOG -DBOOST_SPIRIT_USE_PHOENIX_V3=1 -DBOOST_THREAD_BUILD_DLL=1 -DBOOST_THREAD_DONT_USE_CHRONO=1 -DBOOST_THREAD_NO_LIB=1 -DBOOST_THREAD_POSIX -DBOOST_THREAD_USE_DLL=1 -DDATE_TIME_INLINE -DNDEBUG -D__STDC_CONSTANT_MACROS   -I"." -I"/opt/local/var/macports/build/boost192-54b3655d/work/boost_1_92_0/libs/algorithm/include" -I"/opt/local/var/macports/build/boost192-54b3655d/work/boost_1_92_0/libs/align/include" -I"/opt/local/var/macports/build/boost192-54b3655d/work/boost_1_92_0/libs/array/include" -I"/opt/local/var/macports/build/boost192-54b3655d/work/boost_1_92_0/libs/asio/include" -I"/opt/local/var/macports/build/boost192-54b3655d/work/boost_1_92_0/libs/assert/include" -I"/opt/local/var/macports/build/boost192-54b3655d/work/boost_1_92_0/libs/atomic/include" -I"/opt/local/var/macports/build/boost192-54b3655d/work/boost_1_92_0/libs/bind/include" -I"/opt/local/var/macports/build/boost192-54b3655d/work/boost_1_92_0/libs/chrono/include" -I"/opt/local/var/macports/build/boost192-54b3655d/work/boost_1_92_0/libs/compat/include" -I"/opt/local/var/macports/build/boost192-54b3655d/work/boost_1_92_0/libs/concept_check/include" -I"/opt/local/var/macports/build/boost192-54b3655d/work/boost_1_92_0/libs/container/include" -I"/opt/local/var/macports/build/boost192-54b3655d/work/boost_1_92_0/libs/container_hash/include" -I"/opt/local/var/macports/build/boost192-54b3655d/work/boost_1_92_0/libs/conversion/include" -I"/opt/local/var/macports/build/boost192-54b3655d/work/boost_1_92_0/libs/core/include" -I"/opt/local/var/macports/build/boost192-54b3655d/work/boost_1_92_0/libs/date_time/include" -I"/opt/local/var/macports/build/boost192-54b3655d/work/boost_1_92_0/libs/describe/include" -I"/opt/local/var/macports/build/boost192-54b3655d/work/boost_1_92_0/libs/detail/include" -I"/opt/local/var/macports/build/boost192-54b3655d/work/boost_1_92_0/libs/endian/include" -I"/opt/local/var/macports/build/boost192-54b3655d/work/boost_1_92_0/libs/exception/include" -I"/opt/local/var/macports/build/boost192-54b3655d/work/boost_1_92_0/libs/filesystem/include" -I"/opt/local/var/macports/build/boost192-54b3655d/work/boost_1_92_0/libs/function/include" -I"/opt/local/var/macports/build/boost192-54b3655d/work/boost_1_92_0/libs/function_types/include" -I"/opt/local/var/macports/build/boost192-54b3655d/work/boost_1_92_0/libs/fusion/include" -I"/opt/local/var/macports/build/boost192-54b3655d/work/boost_1_92_0/libs/integer/include" -I"/opt/local/var/macports/build/boost192-54b3655d/work/boost_1_92_0/libs/interprocess/include" -I"/opt/local/var/macports/build/boost192-54b3655d/work/boost_1_92_0/libs/intrusive/include" -I"/opt/local/var/macports/build/boost192-54b3655d/work/boost_1_92_0/libs/iterator/include" -I"/opt/local/var/macports/build/boost192-54b3655d/work/boost_1_92_0/libs/lexical_cast/include" -I"/opt/local/var/macports/build/boost192-54b3655d/work/boost_1_92_0/libs/log/include" -I"/opt/local/var/macports/build/boost192-54b3655d/work/boost_1_92_0/libs/log/src" -I"/opt/local/var/macports/build/boost192-54b3655d/work/boost_1_92_0/libs/move/include" -I"/opt/local/var/macports/build/boost192-54b3655d/work/boost_1_92_0/libs/mp11/include" -I"/opt/local/var/macports/build/boost192-54b3655d/work/boost_1_92_0/libs/mpl/include" -I"/opt/local/var/macports/build/boost192-54b3655d/work/boost_1_92_0/libs/numeric/conversion/include" -I"/opt/local/var/macports/build/boost192-54b3655d/work/boost_1_92_0/libs/optional/include" -I"/opt/local/var/macports/build/boost192-54b3655d/work/boost_1_92_0/libs/parameter/include" -I"/opt/local/var/macports/build/boost192-54b3655d/work/boost_1_92_0/libs/pool/include" -I"/opt/local/var/macports/build/boost192-54b3655d/work/boost_1_92_0/libs/predef/include" -I"/opt/local/var/macports/build/boost192-54b3655d/work/boost_1_92_0/libs/preprocessor/include" -I"/opt/local/var/macports/build/boost192-54b3655d/work/boost_1_92_0/libs/proto/include" -I"/opt/local/var/macports/build/boost192-54b3655d/work/boost_1_92_0/libs/range/include" -I"/opt/local/var/macports/build/boost192-54b3655d/work/boost_1_92_0/libs/ratio/include" -I"/opt/local/var/macports/build/boost192-54b3655d/work/boost_1_92_0/libs/regex/include" -I"/opt/local/var/macports/build/boost192-54b3655d/work/boost_1_92_0/libs/scope/include" -I"/opt/local/var/macports/build/boost192-54b3655d/work/boost_1_92_0/libs/smart_ptr/include" -I"/opt/local/var/macports/build/boost192-54b3655d/work/boost_1_92_0/libs/spirit/include" -I"/opt/local/var/macports/build/boost192-54b3655d/work/boost_1_92_0/libs/system/include" -I"/opt/local/var/macports/build/boost192-54b3655d/work/boost_1_92_0/libs/thread/include" -I"/opt/local/var/macports/build/boost192-54b3655d/work/boost_1_92_0/libs/throw_exception/include" -I"/opt/local/var/macports/build/boost192-54b3655d/work/boost_1_92_0/libs/tokenizer/include" -I"/opt/local/var/macports/build/boost192-54b3655d/work/boost_1_92_0/libs/tuple/include" -I"/opt/local/var/macports/build/boost192-54b3655d/work/boost_1_92_0/libs/type_index/include" -I"/opt/local/var/macports/build/boost192-54b3655d/work/boost_1_92_0/libs/type_traits/include" -I"/opt/local/var/macports/build/boost192-54b3655d/work/boost_1_92_0/libs/typeof/include" -I"/opt/local/var/macports/build/boost192-54b3655d/work/boost_1_92_0/libs/unordered/include" -I"/opt/local/var/macports/build/boost192-54b3655d/work/boost_1_92_0/libs/utility/include" -I"/opt/local/var/macports/build/boost192-54b3655d/work/boost_1_92_0/libs/variant/include" -I"/opt/local/var/macports/build/boost192-54b3655d/work/boost_1_92_0/libs/variant2/include" -I"/opt/local/var/macports/build/boost192-54b3655d/work/boost_1_92_0/libs/winapi/include" -I"libs/config/include"  -c -o "bin.v2/libs/log/build/darwin-16.1.0/release/power_32/threading-multi/visibility-hidden/posix/ipc_reliable_message_queue.o" "/opt/local/var/macports/build/boost192-54b3655d/work/boost_1_92_0/libs/log/src/posix/ipc_reliable_message_queue.cpp"
:info:build In file included from ./boost/interprocess/sync/spin/wait.hpp:28,
:info:build                  from ./boost/interprocess/sync/detail/common_algorithms.hpp:25,
:info:build                  from ./boost/interprocess/sync/interprocess_mutex.hpp:33,
:info:build                  from /opt/local/var/macports/build/boost192-54b3655d/work/boost_1_92_0/libs/log/src/posix/ipc_sync_wrappers.hpp:29,
:info:build                  from /opt/local/var/macports/build/boost192-54b3655d/work/boost_1_92_0/libs/log/src/posix/ipc_reliable_message_queue.cpp:56:
:info:build ./boost/interprocess/detail/os_thread_functions.hpp: In function 'boost::interprocess::ipcdetail::OS_systemwide_thread_id_t boost::interprocess::ipcdetail::get_current_systemwide_thread_id()':
:info:build ./boost/interprocess/detail/os_thread_functions.hpp:332:18: error: 'pthread_threadid_np' was not declared in this scope; did you mean 'pthread_is_threaded_np'?
:info:build   332 | {  uint64_t tid; pthread_threadid_np(NULL, &tid); return tid;   }
:info:build       |                  ^~~~~~~~~~~~~~~~~~~
:info:build       |                  pthread_is_threaded_np
```

**Comment by barracuda156** [comment]
Regression from https://github.com/boostorg/interprocess/commit/0df6182ab33c0b136f0227ad3a7e5d41b6d7c930

FYI @igaztanaga

**Comment by igaztanaga** [comment]
I don't have a old MacOs tester, please let me know if the patch works and if not, please help me with the correct version detection is possible.

**Comment by barracuda156** [comment]
@igaztanaga Thank you! Condition should also exclude powerpc specifically, since Apple Libc exposes this symbol only for x86, so it does not exist when building on 10.6 ppc/rosetta.

**Comment by barracuda156** [comment]
I.e. adding `!defined(__POWERPC__)` (or `!defined(__ppc__)`, since there is no support for ppc64 in 10.6) will fix this.

**Comment by igaztanaga** [comment]
Let's see if this is the final change:

https://github.com/boostorg/interprocess/commit/bcfde01d8210414850e84230ea0dc1c986b8f017
